### Create Post
POST http://localhost:8800/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEyZGQxZjlmOTUyN2JmYzQ0NDUxNWMiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwibmFtZSI6IkpvaG4iLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJfX3YiOjAsInNlc3Npb24iOiI2MmEzNGYwMGM4OWU5N2ExY2QzM2QwNzUiLCJpYXQiOjE2NTQ4Njk3NjAsImV4cCI6MTY1NDg3MDY2MH0.6JEAWshWmaS9dH0G_4sDtiqWbVsGelx9lvyhJr1qhd8

{
    "title": "postTitle 2",
    "body": "post 2 body post body post body post body post body"
}


### Update Post
PATCH http://localhost:8800/api/posts/33840a55-e9a9-4500-9565-7c857f886254
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEyZGQxZjlmOTUyN2JmYzQ0NDUxNWMiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwibmFtZSI6IkpvaG4iLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJfX3YiOjAsInNlc3Npb24iOiI2MmEzNGYwMGM4OWU5N2ExY2QzM2QwNzUiLCJpYXQiOjE2NTQ4Njk3NjAsImV4cCI6MTY1NDg3MDY2MH0.6JEAWshWmaS9dH0G_4sDtiqWbVsGelx9lvyhJr1qhd8

{
    "title": "updated postTitle",
    "body": "post body post body post body post body post body"
}

### Delete Post
DELETE http://localhost:8800/api/posts/59b528d1-60a5-4662-82c7-8758753e4907
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEyZGQxZjlmOTUyN2JmYzQ0NDUxNWMiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwibmFtZSI6IkpvaG4iLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJfX3YiOjAsInNlc3Npb24iOiI2MmEzNTA5YzRlMTU5YTg3YzVjOTY1YWYiLCJpYXQiOjE2NTQ4NzAxNzIsImV4cCI6MTY1NDg3MTA3Mn0.njIhrqMkeJeUSlBuQsspBrGWpWOpyBQpEraBzVXvVYo

### find Post by id
GET http://localhost:8800/api/posts/59b528d1-60a5-4662-82c7-8758753e4907
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEyZGQxZjlmOTUyN2JmYzQ0NDUxNWMiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwibmFtZSI6IkpvaG4iLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJfX3YiOjAsInNlc3Npb24iOiI2MmEzNGYwMGM4OWU5N2ExY2QzM2QwNzUiLCJpYXQiOjE2NTQ4Njk3NjAsImV4cCI6MTY1NDg3MDY2MH0.6JEAWshWmaS9dH0G_4sDtiqWbVsGelx9lvyhJr1qhd8

### find All Posts
GET http://localhost:8800/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEyZGQxZjlmOTUyN2JmYzQ0NDUxNWMiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwibmFtZSI6IkpvaG4iLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJfX3YiOjAsInNlc3Npb24iOiI2MmEzNGYwMGM4OWU5N2ExY2QzM2QwNzUiLCJpYXQiOjE2NTQ4Njk3NjAsImV4cCI6MTY1NDg3MDY2MH0.6JEAWshWmaS9dH0G_4sDtiqWbVsGelx9lvyhJr1qhd8

### find Logged In UsersPosts
GET http://localhost:8800/api/user-posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEyZGQxZjlmOTUyN2JmYzQ0NDUxNWMiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwibmFtZSI6IkpvaG4iLCJjcmVhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTA2LTEwVDA1OjU2OjQ3LjcwOFoiLCJfX3YiOjAsInNlc3Npb24iOiI2MmEzNGYwMGM4OWU5N2ExY2QzM2QwNzUiLCJpYXQiOjE2NTQ4Njk3NjAsImV4cCI6MTY1NDg3MDY2MH0.6JEAWshWmaS9dH0G_4sDtiqWbVsGelx9lvyhJr1qhd8